---
- name: check if binary is already present
  stat:
    path: "{{ promtail_binary_path }}"
  register: promtail_binary

- name: get promtail binary
  block:
    - name: make temporary download folder
      tempfile:
        state: directory
        suffix: .promtail
      register: download_dir

    - name: download promtail binary
      get_url:
        url: "{{ promtail_download_url }}"
        dest: "{{ download_dir.path }}/{{ promtail_download_url | basename }}"
        mode: 644

    - name: unarchive promtail binary
      unarchive:
        src: "{{ download_dir.path }}/{{ promtail_download_url | basename }}"
        dest: "{{ download_dir.path}}"
        remote_src: yes

    - name: move binary in place
      copy:
        remote_src: yes
        src: "{{ download_dir.path}}/promtail-linux-amd64"
        dest: "{{ promtail_binary_path }}"
        mode: 0755
        owner: root
        group: root
      register: promtail_binary_changed

    - name: remove temporary download folder
      file:
        path: "{{ download_dir.path}}"
        state: absent
  when: not promtail_binary.stat.exists or promtail_refresh_binary is defined and promtail_refresh_binary

- name: create promtail system user
  user:
    name: promtail
    shell: /usr/sbin/nologin
    home: "{{ promtail_data_dir }}"
    system: yes
    state: present
    groups:
      - systemd-journal

- name: ensure data directory exists with the proper permissions
  file:
    path: "{{ promtail_data_dir }}"
    state: directory
    owner: promtail
    group: promtail
    mode: 0750

- name: ensure config directory exists
  file:
    path: "{{ promtail_config_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: render promtail configuration
  template:
    src: promtail.yaml.j2
    dest: "{{ promtail_config_path }}"
    mode: 0644
    owner: root
    group: root
  register: promtail_config

- name: render default environment variables
  template:
    src: default.j2
    dest: /etc/default/promtail
    mode: 0644
    owner: root
    group: root
  register: defaults

- name: render systemd unit file
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    mode: 0644
    owner: root
    group: root
  register: systemd

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: enable and start promtail
  systemd:
    name: promtail
    enabled: true
    state: restarted
  when: defaults.changed or systemd.changed or promtail_binary_changed is defined or promtail_config.changed
