---
- name: Add main lenny package source for prometheus server dependencies
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu/ lenny main
    state: present
    filename: lenny-main
    codename: lenny
  when: prometheus_source is defined and prometheus_source == 'lenny'

- name: Update deb package list
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    name:
      - prometheus
    state: latest
    default_release: "{{ prometheus_source | default('focal') }}"
  register: installed

- name: Put prometheus' default config on the host
  template:
    src: default.j2
    dest: /etc/default/prometheus
  register: defaults

- name: Put prometheus' config on the host
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  register: configuration
  tags: prometheus-config

- name: Put prometheus' alerting rules in place
  template:
    src: alerting_rules.yml.j2
    dest: /etc/prometheus/alerting_rules.yml
  register: alerting_rules
  tags: prometheus-config

- name: Put prometheus' recording rules in place
  copy:
    src: recording_rules.yml
    dest: /etc/prometheus/recording_rules.yml
  register: recording_rules
  tags: prometheus-config

- name: Restart and enable prometheus server
  systemd:
    enabled: true
    state: restarted
    name: prometheus
  when: (installed is defined and installed.changed) or (defaults is defined and defaults.changed)

- name: Reload configuration of prometheus server
  systemd:
    state: reloaded
    name: prometheus
  when: ((installed is undefined or not installed.changed) and (defaults is undefined or not defaults.changed)) and (configuration.changed or
    alerting_rules.changed or recording_rules.changed)
  tags: prometheus-config
