# inventory_region1.yaml

all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=15 -o ControlMaster=auto -o ControlPersist=60s'
    # use the apt-cacher-ng proxy on all hosts
    # environment name
    domain: region1-test
    internal_domain: region1-test.internal
    node_user: polkadot
    node_app_name: watr
    node_chain: rococo
    node_parachain_chainspec: https://raw.githubusercontent.com/Watr-Protocol/watr/main/chain-specs/devnet-raw.json # chain spec file if required
    node_binary: "https://github.com/Watr-Protocol/watr/releases/download/v1.2.0/watr-node" # release binary to run on all nodes

  children:
    bastions: {}
    monitoring:
      hosts:
        region1-monitoring-1:
          ansible_user: ubuntu
          ansible_host: region1-monitoring-1.mycompany.com
          # IPs or CIDR ranges allowed to access monitoring (warning: this is in addition to security groups rules)
          domain_name: monitoring.mycompany.com
          rpc_user: monitoring
          rpc_password: xxxxxxxxxxxxxx # some password
          smtp_to: admin@mycompany.com
          monitoring_allowed_ips:
            - 'x.x.x.x' # Some allowed VPN endpoint
          prometheus_retention_days: 31 # 1 months
          prometheus_source: bullseye
          loki_retention_period: 672h # 4 weeks
          rpc_user: region1
          additional_scrape_config_ec2: {}

    archivenodes: {}
    indexnodes: {}
    backupnodes: {}
    validators: {}

    accessnodes:
      hosts:
        region1-rpc-us-1:
          ansible_user: ubuntu
          node_parachain_chain: watr 
          node_parachain_role: rpc
          node_pruning: 0
          ansible_host: test-region1-rpc-1.mycompany.com
          node_custom_options: ["--execution wasm"]


    collators: # example collator with injected aura private key
      hosts:
        region1-collator-1:
          node_parachain_role: collator
          node_custom_options: ["--execution wasm"]
          key_inject_parachain_aura_private_key: "0x0" # inject this private aura key
          ansible_host: region1-collator-1.mycompany.com
