---

- name: update deb package list
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install the package
  apt:
    name:
      - prometheus-alertmanager
    state: latest
    default_release: "{{ prometheus_source | default('focal') }}"
  register: installed


- name: put prometheus-alertmanager' default config on the host
  template:
    src: default.j2
    dest: /etc/default/prometheus-alertmanager
  register: defaults

- name: put prometheus-alertmanager' config on the host
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    owner: root
    group: prometheus
    mode: 0640
  register: configuration
  tags: alertmanager-config


- name: ensure alertmanager's template directory exists
  file:
    path: /etc/prometheus/alertmanager_templates
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: alertmanager-config

- name: set config for amtool
  copy:
    content: |
      {% if domain_name is defined %}
      alertmanager.url: http://localhost:9093/alertmanager/
      {% else %}
      alertmanager.url: http://localhost:9093/
      {% endif %}
    dest: /etc/prometheus/amtool.yml
  tags: amtool-config

- name: restart and enable prometheus-alertmanager server
  systemd:
    enabled: true
    state: restarted
    name: prometheus-alertmanager
  when: (installed is defined and installed.changed) or (defaults is defined and defaults.changed)

- name: reload configuration of prometheus-alertmanager server
  systemd:
    state: reloaded
    name: prometheus-alertmanager
  when: ((installed is undefined or not installed.changed) and (defaults is undefined or not defaults.changed)) and configuration.changed
  tags: alertmanager-config

